// <auto-generated />
using System;
using CncWallStation.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CncWallStation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519083754_AddDataCheckSupport")]
    partial class AddDataCheckSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CncWallStation.Models.Entities.DataCheckRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double>("BimScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("CheckTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<double>("MomScore")
                        .HasColumnType("double");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CheckTime")
                        .HasDatabaseName("IX_DataCheckRecord_CheckTime");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_DataCheckRecord_WallId");

                    b.ToTable("DataCheckRecord", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HostName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ImportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SourceFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("TotalWalls")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsLatest");

                    b.HasIndex("ProjectNumber");

                    b.HasIndex("ProjectNumber", "Version")
                        .IsUnique();

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ValidationErrorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DataCheckGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ErrorCategory")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessageEn")
                        .HasColumnType("text");

                    b.Property<string>("FeatureCategory")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PipelineStage")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<long?>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataCheckGroupId")
                        .HasDatabaseName("IX_ValidationError_DataCheckGroupId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_ValidationError_GroupId");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_ValidationError_WallId");

                    b.ToTable("ValidationError", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.WallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BimJsonData")
                        .IsRequired()
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MomJsonData")
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<int>("PipelineStage")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("WallId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Floor")
                        .HasDatabaseName("IX_Wall_Floor");

                    b.HasIndex("ImportTime")
                        .HasDatabaseName("IX_Wall_ImportTime");

                    b.HasIndex("PipelineStage")
                        .HasDatabaseName("IX_Wall_PipelineStage");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Wall_Priority");

                    b.HasIndex("ProjectNumber")
                        .HasDatabaseName("IX_Wall_ProjectNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Wall_Status");

                    b.HasIndex("ProjectId", "WallId")
                        .IsUnique();

                    b.HasIndex("ProjectNumber", "Status", "Floor")
                        .HasDatabaseName("IX_Wall_ProjectNumber_Status_Floor");

                    b.ToTable("Wall", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.DataCheckRecordEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.WallEntity", "Wall")
                        .WithMany("DataCheckRecords")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ValidationErrorEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.DataCheckRecordEntity", "DataCheckRecord")
                        .WithMany("Errors")
                        .HasForeignKey("DataCheckGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CncWallStation.Models.Entities.WallEntity", "Wall")
                        .WithMany("ValidationErrors")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DataCheckRecord");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.WallEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.ProjectEntity", "Project")
                        .WithMany("Walls")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.DataCheckRecordEntity", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Walls");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.WallEntity", b =>
                {
                    b.Navigation("DataCheckRecords");

                    b.Navigation("ValidationErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
