// <auto-generated />
using System;
using CncWallStation.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CncWallStation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CncWallStation.Models.Entities.DataCheckRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double>("BimScore")
                        .HasColumnType("double");

                    b.Property<DateTime>("CheckTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<double>("MomScore")
                        .HasColumnType("double");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CheckTime")
                        .HasDatabaseName("IX_DataCheckRecord_CheckTime");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_DataCheckRecord_WallId");

                    b.ToTable("DataCheckRecord", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.MachiningExceptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomType")
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("int");

                    b.Property<int>("FrequencyCount")
                        .HasColumnType("int");

                    b.Property<string>("ImprovementSuggestion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhotoPaths")
                        .HasColumnType("TEXT");

                    b.Property<string>("Registrant")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RepairDuration")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("RepairMethod")
                        .HasColumnType("VARCHAR(512)");

                    b.Property<string>("Resolver")
                        .HasColumnType("VARCHAR(64)");

                    b.Property<long>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_MachiningException_WallId");

                    b.ToTable("MachiningException", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.MachiningRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TotalDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_MachiningRecord_WallId");

                    b.ToTable("MachiningRecord", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.OpcWriteRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Opc_GroupId");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_Opc_WallId");

                    b.ToTable("Opc", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.PlcInstructionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("D")
                        .HasColumnType("int");

                    b.Property<int>("F")
                        .HasColumnType("int");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Side")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("T")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("WallId")
                        .HasColumnType("bigint");

                    b.Property<float>("X0")
                        .HasColumnType("float");

                    b.Property<float>("X1")
                        .HasColumnType("float");

                    b.Property<float>("Y0")
                        .HasColumnType("float");

                    b.Property<float>("Y1")
                        .HasColumnType("float");

                    b.Property<float>("Z0")
                        .HasColumnType("float");

                    b.Property<float>("Z1")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_PlcInstruction_WallId");

                    b.HasIndex("WallId", "Side")
                        .HasDatabaseName("IX_PlcInstruction_WallId_Side");

                    b.HasIndex("WallId", "SortOrder")
                        .HasDatabaseName("IX_PlcInstruction_WallId_SortOrder");

                    b.ToTable("PlcInstruction", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HostName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ImportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SourceFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("TotalWalls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectName");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ValidationErrorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DataCheckGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ErrorCategory")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessageEn")
                        .HasColumnType("text");

                    b.Property<string>("FeatureCategory")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PipelineStage")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<long?>("WallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataCheckGroupId")
                        .HasDatabaseName("IX_ValidationError_DataCheckGroupId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_ValidationError_GroupId");

                    b.HasIndex("WallId")
                        .HasDatabaseName("IX_ValidationError_WallId");

                    b.ToTable("ValidationError", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.WallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AuditStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("BimJsonData")
                        .IsRequired()
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<DateTime?>("EndProductionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("MomJsonData")
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<int>("PipelineStage")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("V0.0.0");

                    b.Property<DateTime?>("StartProductionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("WallId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("WallName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuditStatus")
                        .HasDatabaseName("IX_Wall_AuditStatus");

                    b.HasIndex("EndProductionTime")
                        .HasDatabaseName("IX_Wall_EndProductionTime");

                    b.HasIndex("Floor")
                        .HasDatabaseName("IX_Wall_Floor");

                    b.HasIndex("ImportTime")
                        .HasDatabaseName("IX_Wall_ImportTime");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Wall_IsDeleted");

                    b.HasIndex("PipelineStage")
                        .HasDatabaseName("IX_Wall_PipelineStage");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Wall_Priority");

                    b.HasIndex("ProjectName")
                        .HasDatabaseName("IX_Wall_ProjectName");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Wall_Status");

                    b.HasIndex("WallName")
                        .HasDatabaseName("IX_Wall_WallName");

                    b.HasIndex("ProjectId", "WallId")
                        .IsUnique();

                    b.HasIndex("ProjectName", "Status", "Floor")
                        .HasDatabaseName("IX_Wall_ProjectName_Status_Floor");

                    b.ToTable("Wall", (string)null);
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.DataCheckRecordEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.WallEntity", "Wall")
                        .WithMany("DataCheckRecords")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.MachiningExceptionEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.WallEntity", null)
                        .WithMany()
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.MachiningRecordEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.WallEntity", null)
                        .WithMany()
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.PlcInstructionEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.WallEntity", "Wall")
                        .WithMany()
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ValidationErrorEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.DataCheckRecordEntity", "DataCheckRecord")
                        .WithMany("Errors")
                        .HasForeignKey("DataCheckGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CncWallStation.Models.Entities.WallEntity", "Wall")
                        .WithMany("ValidationErrors")
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DataCheckRecord");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.WallEntity", b =>
                {
                    b.HasOne("CncWallStation.Models.Entities.ProjectEntity", "Project")
                        .WithMany("Walls")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.DataCheckRecordEntity", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Walls");
                });

            modelBuilder.Entity("CncWallStation.Models.Entities.WallEntity", b =>
                {
                    b.Navigation("DataCheckRecords");

                    b.Navigation("ValidationErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
